import React, { PropsWithChildren, useState } from "react";
import Navbar from "./Navbar";

import Sidebar from "./Sidebar";
import Head from "next/head";

// Main Layout
const Layout = (props: PropsWithChildren) => {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <>
    <Head>
        <title>Genesis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="grid min-h-screen grid-rows-header bg-zinc-100">
    <div>
      <Navbar onMenuButtonClick={() => setSidebarOpen((prev) => !prev)} />
    </div>
    
    <div className="grid md:grid-cols-sidebar">
      <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />
    </div>
    <div className="container">
      {props.children}
    </div>
  </div>
  </>
  );
};

export default Layout;
