import React, { PropsWithChildren, useState } from "react";
import Navbar from "./Navbar";

import Sidebar from "./Sidebar";


// Main Layout
const Layout = (props: PropsWithChildren)=> {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    <>
    {/* <Head>
        <title>Genesis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
    {/* <div className="grid min-h-screen grid-rows-header bg-zinc-100"> */}
    {/* <div>
      <Navbar onMenuButtonClick={() => setSidebarOpen((prev) => !prev)} />
    </div> */}
    
    {/* <div className="grid md:grid-cols-sidebar">
      <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />
    </div> */}

    {/* <div className=""> */}
    {/* <div className="w-20">
      <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />
    </div> */}

{/* <aside id="default-sidebar" className="left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div className="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
   <div className="grid md:grid-cols-sidebar">
      <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />
    </div>
   </div>
</aside> */}
<div className="grid min-h-screen grid-rows-header bg-zinc-100">
  <Navbar onMenuButtonClick={() => setSidebarOpen((prev) => !prev)} />
  <div className="flex">
      {/* <Navbar onMenuButtonClick={() => setSidebarOpen((prev) => !prev)}/> */}
      {/* p-10 */}
      {/* w-44 fixed left-0 top-20 h-screen bg-slate-700 */}
        <aside className="sm:visible  md:w-44 fixed left-0 h-full bg-black  md:grid-cols-sidebar">
        <Sidebar open={sidebarOpen} setOpen={setSidebarOpen} />
        </aside>
        <main className="flex-1 md:ml-44">
            <div className="bg-black p-10 h-full">
            {props.children}
            </div>
        </main>
    </div>

    {/* <div className="p-4 sm:ml-64">
      {props.children}
    </div> */}
    {/* </div> */}
  </div>

  </>
  );
};

export default Layout;
